# Generated by Django 2.1.2 on 2018-10-11 10:17

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ユーザーID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('is_staff', models.BooleanField(default=False, verbose_name='スタッフ権限')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', api.models.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='MstClass',
            fields=[
                ('class_cd', models.IntegerField(primary_key=True, serialize=False, verbose_name='区分コード')),
                ('class_name', models.CharField(max_length=64, verbose_name='区分名')),
                ('type_1', models.IntegerField(verbose_name='分類1')),
                ('type_2', models.IntegerField(verbose_name='分類2')),
                ('type_3', models.IntegerField(verbose_name='分類3')),
            ],
            options={
                'db_table': 'mst_class',
            },
        ),
        migrations.CreateModel(
            name='MstCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_cd', models.IntegerField(verbose_name='企業コード')),
                ('seq_no', models.IntegerField(verbose_name='連番')),
                ('company_name', models.CharField(max_length=64, unique=True, verbose_name='企業名')),
                ('zip_cd', models.CharField(blank=True, max_length=8, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='住所')),
                ('tel_no', models.CharField(blank=True, max_length=16, verbose_name='電話番号')),
            ],
            options={
                'db_table': 'mst_company',
            },
        ),
        migrations.CreateModel(
            name='MstDB',
            fields=[
                ('db_cd', models.IntegerField(primary_key=True, serialize=False, verbose_name='DBコード')),
                ('db_name', models.CharField(max_length=64, unique=True, verbose_name='DB名')),
                ('class_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MstClass')),
            ],
            options={
                'db_table': 'mst_db',
            },
        ),
        migrations.CreateModel(
            name='MstLanguage',
            fields=[
                ('language_cd', models.IntegerField(primary_key=True, serialize=False, verbose_name='言語コード')),
                ('language_name', models.CharField(max_length=64, unique=True, verbose_name='言語名')),
                ('class_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MstClass')),
            ],
            options={
                'db_table': 'mst_language',
            },
        ),
        migrations.CreateModel(
            name='MstOS',
            fields=[
                ('os_cd', models.IntegerField(primary_key=True, serialize=False, verbose_name='OSコード')),
                ('os_name', models.CharField(max_length=64, unique=True, verbose_name='OS名')),
                ('class_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MstClass')),
            ],
            options={
                'db_table': 'mst_os',
            },
        ),
        migrations.CreateModel(
            name='MstQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_cd', models.IntegerField(verbose_name='資格コード')),
                ('seq_no', models.IntegerField(verbose_name='連番')),
                ('qualification_name', models.CharField(max_length=64, unique=True, verbose_name='資格名')),
                ('class_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MstClass')),
            ],
            options={
                'db_table': 'mst_qualification',
            },
        ),
        migrations.CreateModel(
            name='MstTool',
            fields=[
                ('tool_cd', models.IntegerField(primary_key=True, serialize=False, verbose_name='ツールコード')),
                ('tool_name', models.CharField(max_length=64, unique=True, verbose_name='ツール名')),
                ('class_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MstClass')),
            ],
            options={
                'db_table': 'mst_tool',
            },
        ),
        migrations.CreateModel(
            name='AccountToken',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('token', models.CharField(max_length=40)),
                ('access_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TblPerson',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_name', models.CharField(blank=True, max_length=16, verbose_name='姓')),
                ('last_name_kana', models.CharField(blank=True, max_length=16, verbose_name='姓かな')),
                ('first_name', models.CharField(blank=True, max_length=16, verbose_name='名')),
                ('first_name_kana', models.CharField(blank=True, max_length=16, verbose_name='名かな')),
                ('initial', models.CharField(blank=True, max_length=3, verbose_name='イニシャル')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('nearest_station', models.CharField(blank=True, max_length=32, verbose_name='最寄駅')),
                ('health', models.TextField(blank=True, max_length=256, verbose_name='健康状態')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='mstcompany',
            unique_together={('company_cd', 'seq_no')},
        ),
        migrations.AlterUniqueTogether(
            name='mstclass',
            unique_together={('type_1', 'type_2', 'type_3')},
        ),
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='tblperson',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.MstCompany'),
        ),
        migrations.AlterUniqueTogether(
            name='mstqualification',
            unique_together={('qualification_cd', 'seq_no')},
        ),
    ]
